USE LF_MANUTENCAODB

ALTER VIEW VW_ORDER_SERVICE

--View para criar tabela de ordens de serviço
-- 
	AS
		SELECT F.NM_FUNCIONARIO, E.NM_EQUIPAMENTO, R.DT_RESERVA, R.DT_ENTREGA, R.DE_OBS, ID_RESERVA
		FROM RESERVA R
			JOIN FUNCIONARIO F ON R.ID_FUNCIONARIO = F.ID_FUNCIONARIO
			JOIN EQUIPAMENTO E ON R.ID_EQUIPAMENTO = E.ID_EQUIPAMENTO



SP_HELPTEXT VW_ORDER_SERVICE