USE LF_MANUTENCAODB

-- Primeiro passo é criar as tabelas para o projeto
-- Criar tabelas para Setor de equipamento, Funcionários Habilitados, Equipamentos, e Reserva


CREATE TABLE SETOR(
	ID_SETOR INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NM_SETOR VARCHAR(200),
	IS_ACTIVE BIT NOT NULL
	);
	
GO


CREATE TABLE FUNCIONARIO(
	ID_FUNCIONARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NM_FUNCIONARIO VARCHAR(200) NOT NULL,
	ID_SETOR INT FOREIGN KEY REFERENCES SETOR(ID_SETOR),
	DE_SENHA VARCHAR(200)
	);

GO

CREATE TABLE EQUIPAMENTO(
	ID_EQUIPAMENTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NM_EQUIPAMENTO VARCHAR(200) NOT NULL,
	ID_SETOR INT FOREIGN KEY REFERENCES SETOR(ID_SETOR),
	CODE_EQUIPAMENTO VARCHAR(200) NOT NULL);

GO

CREATE TABLE RESERVA(
	ID_RESERVA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_EQUIPAMENTO INT FOREIGN KEY REFERENCES EQUIPAMENTO(ID_EQUIPAMENTO),
	ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIO(ID_FUNCIONARIO),
	DT_RESERVA DATETIME,
	DT_ENTREGA DATETIME,
	DE_OBS VARCHAR(1000));
GO
