USE LF_MANUTENCAODB

-- Complemento de colunas para a tabela de funcionarios 

SELECT * FROM FUNCIONARIO

ALTER TABLE FUNCIONARIO
	ADD DE_FUNCIONARIO VARCHAR(200)
GO
ALTER TABLE FUNCIONARIO
	ADD NM_ADRESS VARCHAR(500)
GO

ALTER TABLE FUNCIONARIO
	ADD NU_REGISTRATION VARCHAR(50)
GO
ALTER TABLE FUNCIONARIO
	ADD NU_PHONE VARCHAR(50)